"""Export module — generates ctx.md for AI assistants."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from ctx.analyzers.architecture import DIR_PURPOSES, ArchitectureResult
from ctx.scanner.env import EnvResult
from ctx.scanner.filesystem import FilesystemResult
from ctx.scanner.packages import PackageResult


def generate_context_markdown(
    fs: FilesystemResult,
    pkg: PackageResult,
    env: EnvResult,
    arch: ArchitectureResult,
    target: str = "generic",
) -> str:
    """Generate a markdown context file optimized for AI assistants.

    Args:
        fs: Filesystem scan results.
        pkg: Package scan results.
        env: Environment scan results.
        arch: Architecture analysis results.
        target: Target AI assistant (generic, chatgpt, claude, gemini, cursor, codex).

    Returns:
        Markdown string ready to be saved or copied.
    """
    lines: list[str] = []

    project_name = pkg.project_name or fs.root.name
    now = datetime.now().strftime("%Y-%m-%d")

    # Preamble based on target
    preambles = {
        "chatgpt": (
            f"You are helping me work on **{project_name}**. "
            "Below is the full project context. Use this to answer my questions accurately. "
            "Always reference specific files and paths when explaining.\n"
        ),
        "claude": (
            f"<context>\nThis is the complete project context for **{project_name}**. "
            "Reference specific file paths and architectural patterns when answering.\n</context>\n"
        ),
        "gemini": (
            f"Context: You are assisting with the **{project_name}** project. "
            "The following is a comprehensive project overview. "
            "Use it to provide accurate, file-specific guidance.\n"
        ),
        "cursor": (
            f"# Project Context: {project_name}\n\n"
            "Use this file as your primary reference for understanding the codebase.\n"
        ),
        "codex": (
            f"# {project_name} — Project Context\n\n"
            "This document describes the project structure, dependencies, and architecture. "
            "Reference it when making changes.\n"
        ),
    }

    if target in preambles:
        lines.append(preambles[target])
    else:
        lines.append(f"# {project_name}\n")

    lines.append(f"_Generated by ctx on {now}_\n")

    # Overview
    lines.append("## Overview\n")
    if arch.project_type:
        lines.append(f"- **Type**: {arch.project_type}")
    if pkg.language:
        lines.append(f"- **Language**: {pkg.language}")
    if pkg.framework:
        ver = f" {pkg.framework_version}" if pkg.framework_version else ""
        lines.append(f"- **Framework**: {pkg.framework}{ver}")
    if pkg.package_manager:
        lines.append(f"- **Package Manager**: {pkg.package_manager}")
    lines.append(f"- **Files**: {fs.total_files}")
    lines.append(f"- **Lines of Code**: {fs.total_lines:,}")
    lines.append("")

    # Directory Structure
    if fs.main_folders:
        lines.append("## Directory Structure\n")
        lines.append("```")
        for folder in fs.main_folders:
            dirname = folder.rstrip("/")
            purpose = DIR_PURPOSES.get(dirname, "")
            if purpose:
                lines.append(f"{folder:<24} # {purpose}")
            else:
                lines.append(folder)
        lines.append("```\n")

    # Important Files
    if fs.important_files:
        lines.append("## Important Files\n")
        for imp_file in fs.important_files:
            lines.append(f"- `{imp_file}`")
        lines.append("")

    # Entrypoints
    if arch.entrypoints:
        lines.append("## Entrypoints\n")
        for ep in arch.entrypoints:
            lines.append(f"- `{ep}`")
        lines.append("")

    # Dependencies
    if pkg.dependencies:
        lines.append("## Key Dependencies\n")
        for name in list(pkg.dependencies.keys())[:30]:
            lines.append(f"- {name}")
        if len(pkg.dependencies) > 30:
            lines.append(f"- _… +{len(pkg.dependencies) - 30} more_")
        lines.append("")

    # Environment Variables
    if env.variables:
        lines.append("## Environment Variables\n")
        for var in env.variables:
            lines.append(f"- `{var}`")
        lines.append("")

    # Architecture Summary
    if arch.summary_points:
        lines.append("## Architecture Summary\n")
        for point in arch.summary_points:
            lines.append(f"- {point}")
        lines.append("")

    # Architecture Layers
    if arch.architecture_layers:
        lines.append("## Architecture Layers\n")
        lines.append("```")
        lines.append(" → ".join(arch.architecture_layers))
        lines.append("```\n")

    # File tree (compact)
    lines.append("## File Tree\n")
    lines.append("```")
    for file_info in fs.files[:100]:
        lines.append(file_info.relative)
    if len(fs.files) > 100:
        lines.append(f"… +{len(fs.files) - 100} more files")
    lines.append("```\n")

    return "\n".join(lines)


def export_context(
    fs: FilesystemResult,
    pkg: PackageResult,
    env: EnvResult,
    arch: ArchitectureResult,
    output_path: Path | None = None,
    target: str = "generic",
) -> Path:
    """Export context to a markdown file.

    Args:
        output_path: Where to write the file. Defaults to ctx.md in project root.
        target: Target AI assistant format.

    Returns:
        Path to the written file.
    """
    if output_path is None:
        output_path = fs.root / "ctx.md"

    content = generate_context_markdown(fs, pkg, env, arch, target=target)
    output_path.write_text(content, encoding="utf-8")

    return output_path
